version: '3'

services:
  gateway-service:
    container_name: gateway-service
    build: # 服务的 Docker 构建文件位置
      context: ./gateway-service
      dockerfile: Dockerfile
    #    ports:
    #      - "8080:8080"
    volumes:
      - /data/volumes/service-log/gateway-service:/opt/logs
    environment:
      TZ: Asia/Shanghai # 设置时区
    networks:
      - mynetwork

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    #    ports:
    #      - "8090:8090"
    volumes:
      - /data/volumes/service-log/auth-service:/opt/logs
    environment:
      TZ: Asia/Shanghai # 设置时区
    networks:
      - mynetwork
    depends_on: # 本服务依赖的服务，控制启动先后顺序
      - gateway-service

  user-service:
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    #    ports:
    #      - "8120:8120"
    volumes:
      - /data/volumes/service-log/user-service:/opt/logs
    environment:
      TZ: Asia/Shanghai # 设置时区
    networks:
      - mynetwork
    depends_on:
      - auth-service

  content-service:
    container_name: content-service
    build:
      context: ./content-service
      dockerfile: Dockerfile
    #    ports:
    #      - "8150:8150"
    volumes:
      - /data/volumes/service-log/content-service:/opt/logs
    environment:
      TZ: Asia/Shanghai # 设置时区
    networks:
      - mynetwork
    depends_on:
      - gateway-service
      - user-service
      - notify-service

  notify-service:
    container_name: notify-service
    build:
      context: ./notify-service
      dockerfile: Dockerfile
    #    ports:
    #      - "8110:8110"
    volumes:
      - /data/volumes/service-log/notify-service:/opt/logs
    environment:
      TZ: Asia/Shanghai # 设置时区
    networks:
      - mynetwork
    depends_on:
      - gateway-service
      - user-service

  file-service:
    container_name: file-service
    build:
      context: ./file-service
      dockerfile: Dockerfile
    #    ports:
    #      - "8160:8160"
    volumes:
      - /data/volumes/service-log/file-service:/opt/logs
    environment:
      TZ: Asia/Shanghai # 设置时区
    networks:
      - mynetwork
    depends_on:
      - gateway-service
      - user-service

# 网络，不定义的话就是默认网络
networks:
  mynetwork:
    external: true