version: '3'

services:
  mysql:
    image: mysql:8.0.40 # 使用的镜像
    container_name: mysql # 启动的实例名称
    environment:
      MYSQL_ROOT_PASSWORD: youyu1233 # root 用户密码
      TZ: Asia/Shanghai # 设置时区
    ports:
      - "3306:3306" # 端口映射
    volumes:
      - /data/volumes/mysql/log:/var/log/mysql
      - /data/volumes/mysql/data:/var/lib/mysql # 将数据目录挂载到本地目录以进行持久化
      - /data/volumes/mysql/conf:/etc/mysql/conf.d
    #      - ./mysql-init:/docker-entrypoint-initdb.d # 启动脚本
    restart: always # 崩溃后自动重启
    networks:
      - mynetwork # 指定网络

  redis:
    image: redis:7
    container_name: redis
    environment:
      TZ: Asia/Shanghai # 设置时区
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    volumes:
      - /data/volumes/redis/data:/data # 持久化
      - /data/volumes/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  rabbitmq:
    image: rabbitmq:3.12.6-management # 支持管理面板的消息队列
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: youyu1233
      TZ: Asia/Shanghai # 设置时区
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ Dashboard 端口
    volumes:
      - /data/volumes/rabbitmq:/var/lib/rabbitmq # 持久化
    networks:
      - mynetwork

  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos
    environment:
      MODE: standalone # 单节点模式启动
      PREFER_HOST_MODE: hostname # 支持 hostname
      TZ: Asia/Shanghai # 设置时区
      NACOS_AUTH_ENABLE: true # 启用鉴权
      NACOS_AUTH_USER: nacos # 设置管理员账号
      NACOS_AUTH_PASSWORD: nacos1233 # 设置管理员密码
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - /data/volumes/nacos/data:/home/nacos/data
      - /data/volumes/nacos/conf:/home/nacos/conf
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true