version: '3'

services:
  gateway-service:
    container_name: gateway-service
    build: # 服务的 Docker 构建文件位置
      context: ./gateway-service
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    #    ports:
    #      - "8080:8080"
    volumes:
      - /data/volumes/service-log/gateway-service:/opt/logs
    environment:
      TZ: Asia/Shanghai # 设置时区
    networks:
      - mynetwork

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    #    ports:
    #      - "8090:8090"
    volumes:
      - /data/volumes/service-log/auth-service:/opt/logs
    environment:
      TZ: Asia/Shanghai # 设置时区
    networks:
      - mynetwork
    depends_on: # 本服务依赖的服务，控制启动先后顺序
      - gateway-service

  user-service:
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    #    ports:
    #      - "8120:8120"
    volumes:
      - /data/volumes/service-log/user-service:/opt/logs
    environment:
      TZ: Asia/Shanghai # 设置时区
    networks:
      - mynetwork
    depends_on:
      - auth-service

  content-service:
    container_name: content-service
    build:
      context: ./content-service
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    #    ports:
    #      - "8150:8150"
    volumes:
      - /data/volumes/service-log/content-service:/opt/logs
    environment:
      TZ: Asia/Shanghai # 设置时区
    networks:
      - mynetwork
    depends_on:
      - gateway-service
      - user-service
      - infra-service

  infra-service:
    container_name: infra-service
    build:
      context: ./infra-service
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    #    ports:
    #      - "8110:8110"
    volumes:
      - /data/volumes/service-log/infra-service:/opt/logs
    environment:
      TZ: Asia/Shanghai # 设置时区
    networks:
      - mynetwork
    depends_on:
      - gateway-service
      - user-service
      -
# 网络，不定义的话就是默认网络
networks:
  mynetwork:
    external: true