server:
  port: 8110
spring:
  application:
    name: mail-service
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.79.236:8848
  profiles:
    active: '@environment@'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.79.236:3306/youyu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: youyu1233
    hikari:
      minimum-idle: 3
      maximum-pool-size: 20
      max-lifetime: 30000 # 不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1
  redis:
    host: 124.222.79.236
    port: 6379
    password: youyu1233
    database: 0 #操作的是0号数据库
    timeout: 60s
    lettuce:
      shutdown-timeout: 100
      # pool:
      #   max-idle: 30
      #   max-active: 8
      #   max-wait: 10000
      #   min-idle: 10
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  mail:
    host: smtp.163.com #发送邮件服务器
    username: harunayouyu@163.com #网易邮箱
    password: QXOEZVKXRLPFVGMC #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #465或者994
    nickname: 有语
    from: harunayouyu@163.com  #发送邮件的地址，和上面username一致
    #    properties.mail.display.sendmail: 有语 #可以任意
    #    properties.mail.display.sendname: 有语 #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true #开启SSL
    default-encoding: utf-8
logging:
  level:
    com.youyu.mapper: debug
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
    banner: off # 关闭mybatisplus启动图标
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true
aliyun:
  oss:
    endpoint: sts.cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4GByNYLu8m45X7ciiHVP # 访问身份验证中用到用户标识
    accessKeySecret: AGjk1izsAJl9OPPcUgC6CSlfZysXJT # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucket: youyu-source # oss的存储空间
    roleArn: acs:ram::1522211879603568:role/ramosstest
    host: https://youyu-source.oss-cn-beijing.aliyuncs.com
    endpointRAM: sts.cn-beijing.aliyuncs.com
    accessKeyIdRAM: LTAI5tQ6oxmqs9vPvgYkkzsh
    accessKeySecretRAM: hUSWofhYLsF7b1hPTQCgAeOtJqFmUR
    policy:
      expire: 300 # 签名有效期(S)
      maxSize: 10 # 上传文件大小(M)