<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>youyu-cloud</artifactId>
        <groupId>com.youyu</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <packaging>pom</packaging>
    <modules>
        <module>infra-service-api</module>
        <module>infra-service-core</module>
    </modules>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>infra-service</artifactId>

    <description>
        基础设施服务。邮件推送、OSS权限申请、日志入库、消息队列
    </description>

    <dependencies>

    </dependencies>
</project>
